### ISSUE TITLE
[epic] Things to improve as of Jan 2019

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website#184]
* [ ] No way to link to sections of specs (no anchor option - there was in the old version!)
* [ ] Magical Table of contents on left is very annoying ...
* [ ] Top of page navbar does not have the main links for users (stuff hidden in an accordion)

Misc

* [ ] Black theme has a poor feel
* [ ] Dubious about the logo
* [ ] Font is tough to read (very small) and ugly - old specs site was more readable
* [ ]

**Comment by pwalsh** [comment]
Thanks @rufuspollock 

It is great to get this all written out so we can discuss and work out how we can make changes that are widely agreed on.

**Comment by rgieseke** [comment]
Great discussion! I see frictionlessdata.io as the page i send/link people to when i build/promote Data Packages. In my opinion it would be great to see an example on the homepage (for a typical example CSV + JSON, though there can be others) and then some text elaborating. Like a Programming Language homepage it should have an example right on top, like e.g. on python.org
No need for a video or big photos, in general i like the light design.

Maybe there is a request for this somewhere, but easy fulltext search in the specs would be awsome :-)

**Comment by lwinfree** [comment]
I like the newer design overall, especially the color theme and the icons, but agree that there are some things that can be improved:
- I find the video useful, but would move it elsewhere & perhaps have a code example on top (like rgieseke suggests above)
- I also don't really like the magic table of contents
- agree we need a better navbar
- the text font is way too small
- I'd also love to have the software page redone so that the libraries, apps, "universe" are each on a separate page *with a separate URL* so they can be shared more easily

**Comment by rufuspollock** [comment]
@lwinfree i agree :smile: -- though still not sure about the design tbh (full on black is unusual!)

@rgieseke thanks for the feedback and all good points.

**Comment by lwinfree** [comment]
Adding to this issue list that I propose removing the newsletter sign up as 1) we don't write a newsletter and 2) I don't think it is GDPR-compliant
