### ISSUE TITLE
Merge fellows.frictionlessdata.io/blog/ into frictionlessdata.io/blog/

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/website#189]
@lwinfree what do you think of merging the Frictionless Data Fellows blog into the main site blog (with an appropriate tag so you can have a dedicated page to get all the posts).

Why? We are generally aiming to reduce the number of difference entry points so that people find stuff more easily (e.g. I did not even know about the fellows blogs ...). It would also increase the audience for these blog posts

## Tasks

* [x] Agree whether or not to do this
* [ ] If so, copy over the posts
* [ ] ~~Implement redirect on fellows site to frictionlessdata.io~~

**Comment by roll** [comment]
I think it might have sense even to cross-post (of course not DRY) but TBH I had no idea that fellows has a really live blog

**Comment by lwinfree** [comment]
@roll +1. Also, figuring out the fellows site is on my 6-month to-do list.

**Comment by roll** [comment]
We're doing it here - https://github.com/frictionlessdata/frictionlessdata.io/issues/758
